version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && echo yes | python manage.py collectstatic
      && gunicorn candelasoft.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - ./:/code/
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - candelasoft_networks

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - candelasoft_networks

  worker:
    build: .
    command: celery -A candelasoft worker --loglevel=info -Q celery,default
    volumes:
      - ./:/code/
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - candelasoft_networks

  celery-beat:
    build: .
    command: >
      celery -A candelasoft beat
      --loglevel=info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/code/
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - candelasoft_networks

  flower:
    build: .
    command: >
      celery -A candelasoft flower
      --address=0.0.0.0
      --port=5555
      --loglevel=info
    volumes:
      - ./:/code/
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - candelasoft_networks

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - candelasoft_networks

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  candelasoft_networks:
    driver: bridge
